# Generated by Django 2.1.2 on 2019-02-17 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField()),
                ('plan_type', models.CharField(choices=[('', 'Choose your plan'), ('premium', 'Premium Plan (N1000 - N5000)'), ('ulimate', 'Ultimate Plan (N6000 - Above)')], max_length=30)),
                ('text', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
