# Generated by Django 2.1.2 on 2018-11-11 20:50

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 11, 20, 50, 6, 860271, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_create',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
